use std::env;
use std::fs;
use std::io::Write;
use std::path::PathBuf;

fn main() {
    // Where to write the generated Rust file.
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let dest_path = out_dir.join("params_generated.rs");

    // Path to the original RDKit Params.cpp file relative to the workspace root.
    let workspace_root = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap())
        .parent()
        .unwrap() // crates
        .parent()
        .unwrap() // workspace root
        .join("rdkit/Code/ForceField/UFF/Params.cpp");

    let cpp_source = fs::read_to_string(&workspace_root).expect("read Params.cpp");

    // Extract the defaultParamData string literal content.
    let default_param_data = extract_default_param_data(&cpp_source)
        .expect("failed to extract defaultParamData string constant");

    // Parse tab-separated lines into fields.
    let params_map = parse_param_table(&default_param_data);

    // Generate Rust code with phf_map!
    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs – DO NOT EDIT\n");
    // once_cell already imported in the top-level lib, but we need it here inside generated
    // module scope. We will not re-import to avoid duplicate-import warnings; instead we rely
    // on the outer scope import.
    code.push_str("use phf::phf_map;\n\n");
    code.push_str("#[derive(Clone, Copy, Debug, serde::Serialize, serde::Deserialize)]\n");
    code.push_str("pub struct AtomParams {\n");
    code.push_str("    pub r1: f64,\n    pub theta0: f64,\n    pub x1: f64,\n    pub d1: f64,\n    pub zeta: f64,\n    pub z1: f64,\n    pub v_i: f64,\n    pub u_j: f64,\n    pub xi: f64,\n    pub hardness: f64,\n    pub radius: f64,\n}\n\n");

    code.push_str("pub static PARAMS: Lazy<phf::Map<&'static str, AtomParams>> = Lazy::new(|| {\n    phf_map! {\n");
    for (label, p) in &params_map {
        // Helper to guarantee that literal string contains at least one decimal point so that
        // Rust recognises it as a float constant.
        fn lit(v: f64) -> String {
            const PI: f64 = std::f64::consts::PI;
            const FRAC_PI_2: f64 = std::f64::consts::FRAC_PI_2;
            if (v - PI).abs() < 1e-3 {
                "std::f64::consts::PI".to_string()
            } else if (v - FRAC_PI_2).abs() < 1e-3 {
                "std::f64::consts::FRAC_PI_2".to_string()
            } else {
                let mut s = format!("{}", v);
                if !s.contains('.') && !s.contains('e') && !s.contains('E') {
                    s.push('.');
                }
                s
            }
        }
        code.push_str(&format!(
            "        \"{}\" => AtomParams {{ r1: {}, theta0: {}, x1: {}, d1: {}, zeta: {}, z1: {}, v_i: {}, u_j: {}, xi: {}, hardness: {}, radius: {} }},\n",
            label,
            lit(p.r1),
            lit(p.theta0),
            lit(p.x1),
            lit(p.d1),
            lit(p.zeta),
            lit(p.z1),
            lit(p.v_i),
            lit(p.u_j),
            lit(p.xi),
            lit(p.hardness),
            lit(p.radius)
        ));
    }
    code.push_str("    }\n});\n");

    // Write generated code file.
    fs::File::create(&dest_path)
        .and_then(|mut f| f.write_all(code.as_bytes()))
        .expect("write params_generated.rs");

    // Re-run build script if the original file changes.
    println!("cargo:rerun-if-changed={}", workspace_root.display());
}

fn extract_default_param_data(cpp: &str) -> Option<String> {
    use regex::Regex;
    let re_start = Regex::new(r"const\s+std::string\s+defaultParamData\s*=\s*").unwrap();
    let start_idx = re_start.find(cpp)?.end();
    // We are now right after '='; collect until the first ';' at top-level.
    let rest = &cpp[start_idx..];

    let mut in_string = false;
    let mut escaped = false;
    let mut collected = String::new();
    for c in rest.chars() {
        if !in_string {
            if c == '"' {
                in_string = true;
            } else if c == ';' {
                break;
            }
        } else if escaped {
            collected.push(match c {
                'n' => '\n',
                't' => '\t',
                'r' => '\r',
                '\\' => '\\',
                '"' => '"',
                other => other,
            });
            escaped = false;
        } else if c == '\\' {
            escaped = true;
        } else if c == '"' {
            // end of segment, next char maybe \n indent etc. we need to look for another quoted string.
            in_string = false;
            continue;
        } else {
            collected.push(c);
        }
    }
    Some(collected)
}

#[derive(Debug)]
struct ParamValues {
    r1: f64,
    theta0: f64,
    x1: f64,
    d1: f64,
    zeta: f64,
    z1: f64,
    v_i: f64,
    u_j: f64,
    xi: f64,
    hardness: f64,
    radius: f64,
}

fn parse_param_table(data: &str) -> std::collections::BTreeMap<String, ParamValues> {
    let mut map = std::collections::BTreeMap::new();
    for line in data.lines() {
        if line.trim().is_empty() || line.starts_with('#') {
            continue;
        }
        let mut fields = line.split('\t');
        let label = fields.next().unwrap().to_string();
        let r1: f64 = fields.next().unwrap().parse().unwrap();
        let theta0_deg: f64 = fields.next().unwrap().parse().unwrap();
        let theta0 = theta0_deg.to_radians();
        let x1: f64 = fields.next().unwrap().parse().unwrap();
        let d1: f64 = fields.next().unwrap().parse().unwrap();
        let zeta: f64 = fields.next().unwrap().parse().unwrap();
        let z1: f64 = fields.next().unwrap().parse().unwrap();
        let v_i: f64 = fields.next().unwrap().parse().unwrap();
        let u_j: f64 = fields.next().unwrap().parse().unwrap();
        let xi: f64 = fields.next().unwrap().parse().unwrap();
        let hardness: f64 = fields.next().unwrap().parse().unwrap();
        let radius: f64 = fields.next().unwrap().parse().unwrap();

        map.insert(
            label,
            ParamValues {
                r1,
                theta0,
                x1,
                d1,
                zeta,
                z1,
                v_i,
                u_j,
                xi,
                hardness,
                radius,
            },
        );
    }
    map
}
